import React from 'react';
import {
  PlusOutlined,
  SearchOutlined,
  RedoOutlined,
  WarningOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  UserOutlined,
  PhoneOutlined,
  MailOutlined,
  ExclamationCircleOutlined,
  ExclamationCircleFilled,
  SettingOutlined,
  AreaChartOutlined,
  RobotOutlined,
  DownOutlined,
  BarsOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  CaretUpOutlined,
  TeamOutlined,
  FundViewOutlined,
  UserSwitchOutlined,
  ReconciliationOutlined,
  ToolOutlined,
  SafetyCertificateOutlined,
  DatabaseOutlined,
  PlusCircleOutlined,
  RadarChartOutlined,
  AuditOutlined,
  CalculatorOutlined,
  DeploymentUnitOutlined,
  CloudDownloadOutlined,
  CloudUploadOutlined,
} from '@ant-design/icons';


export const icon = {
  menuFold: <MenuFoldOutlined />,
  menuUnfold: <MenuUnfoldOutlined />,
  bars: <BarsOutlined />,
  plus: <PlusOutlined />,
  plusCircle: <PlusCircleOutlined />,
  search: <SearchOutlined />,
  redo: <RedoOutlined />,
  warning: <WarningOutlined />,
  checkCircle: <CheckCircleOutlined />,
  closeCircle: <CloseCircleOutlined />,
  user: <UserOutlined />,
  phone: <PhoneOutlined />,
  mail: <MailOutlined />,
  circle: <ExclamationCircleOutlined />,
  circleFilled: <ExclamationCircleFilled />,
  setting: <SettingOutlined />,
  dashboard: <AreaChartOutlined />,
  robot: <RobotOutlined />,
  down: <DownOutlined />,
  arrowsUp: <CaretUpOutlined />,
  teamOutlined: <TeamOutlined />,
  fundViewOutlined: <FundViewOutlined />,
  userSwitchOutlined: <UserSwitchOutlined />,
  toolOutlined: <ToolOutlined />,
  SafetyCertificateOutlined: <SafetyCertificateOutlined />,
  DatabaseOutlined:  <DatabaseOutlined />,
  radarChartOutlined: <RadarChartOutlined />,
  auditOutlined: <AuditOutlined />,
  calculatorOutlined: <CalculatorOutlined />,
  DeploymentUnitOutlined: <DeploymentUnitOutlined />,
  ReconciliationOutlined: <ReconciliationOutlined/>,
  CloudDownloadOutlined: <CloudDownloadOutlined />,
  CloudUploadOutlined: <CloudUploadOutlined />
};
